platform :ios, '9.0'
use_frameworks!

def all_pods
    pod 'Alamofire', '4.4.0'
    pod 'SDWebImage', '3.8.2'
    pod 'AlamofireObjectMapper', '4.1.0'
end

target 'The Wild Card App' do
  all_pods
end

target 'The Wild Card AppTests' do
    all_pods
end

target 'The Wild Card AppUITests' do
    all_pods
end
