//
//  FilterProtocols.swift
//  The Wild Card App
//
//  Created Tolga Caner on 18/08/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FilterWireframeProtocol: class {

}
//MARK: Presenter -
protocol FilterPresenterProtocol: class {

    var interactor: FilterInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol FilterInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol FilterInteractorInputProtocol: class {

    var presenter: FilterInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol FilterViewProtocol: class {

    var presenter: FilterPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
