//
//  FilterRouter.swift
//  The Wild Card App
//
//  Created Tolga Caner on 18/08/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterRouter: FilterWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FilterViewController(nibName: nil, bundle: nil)
        let interactor = FilterInteractor()
        let router = FilterRouter()
        let presenter = FilterPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
