//
//  FilterViewController.swift
//  The Wild Card App
//
//  Created Tolga Caner on 18/08/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterViewController: UIViewController, FilterViewProtocol {

	var presenter: FilterPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func btnLocationAction(_ sender: UIButton) {
    }
    
    @IBAction func btnEthnicityAction(_ sender: UIButton) {
    }

    @IBAction func btnSwitchAction(_ sender: UISwitch) {
        
    }
    @IBAction func ageValueChanged(_ sender: Any) {
        
    }
}
