//
//  FilterInteractor.swift
//  The Wild Card App
//
//  Created Tolga Caner on 18/08/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterInteractor: FilterInteractorInputProtocol {

    weak var presenter: FilterInteractorOutputProtocol?
}
