//
//  FilterPresenter.swift
//  The Wild Card App
//
//  Created Tolga Caner on 18/08/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterPresenter: FilterPresenterProtocol, FilterInteractorOutputProtocol {

    weak private var view: FilterViewProtocol?
    var interactor: FilterInteractorInputProtocol?
    private let router: FilterWireframeProtocol

    init(interface: FilterViewProtocol, interactor: FilterInteractorInputProtocol?, router: FilterWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
