//
//  RootRouter.swift
//  The Wild Card App
//
//  Created Tolga Caner on 26/06/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RootRouter: RootWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    func presentInitialScreen(in window: UIWindow) {
        LoadingManager.prepare()
        window.makeKeyAndVisible()
        window.rootViewController = WildcardsRouter.createModule()
    }
}
