//
//  WildcardsViewController.swift
//  The Wild Card App
//
//  Created Tolga Caner on 26/06/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WildcardsViewController: UIViewController {

	var presenter: WildcardsPresenterProtocol?
    @IBOutlet weak var wildcardContainerView: WildcardContainer!
    @IBOutlet weak var labelCardsLeft: UILabel!

	override func viewDidLoad() {
        super.viewDidLoad()
        self.wildcardContainerView.cardCountDelegate = self //labelCardsLeft
        presenter?.viewLoaded()
    }
    
}


extension WildcardsViewController : WildcardsViewProtocol {
    
    func setWildcards(_ wildcards : [WildcardEntity]) {
        wildcardContainerView.cardsData = wildcards
        self.updateCardCount(val: wildcards.count)
    }
    
    func showNoUsersAlert() {
        let alert = UIAlertController(title: "Error", message: "Error fetching users.", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Ok", style: .cancel))
        self.present(alert, animated: true, completion: nil)
    }
}

extension WildcardsViewController : CardCountDelegate {
    func updateCardCount(val : Int) {
        self.labelCardsLeft.text = "Cards left: \(val)"
    }
}
