//
//  WildcardsRouter.swift
//  The Wild Card App
//
//  Created Tolga Caner on 26/06/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WildcardsRouter: WildcardsWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = WildcardsViewController(nibName: nil, bundle: nil)
        let interactor = WildcardsInteractor()
        let router = WildcardsRouter()
        let presenter = WildcardsPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.output = presenter
        router.viewController = view

        return view
    }
}
