//
//  WildcardsProtocols.swift
//  The Wild Card App
//
//  Created Tolga Caner on 26/06/2017.
//  Copyright © 2017 Tolga Caner. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WildcardsWireframeProtocol: class {

}
//MARK: Presenter -
protocol WildcardsPresenterProtocol: class {

    var interactor: WildcardsInteractorInputProtocol? { get set }
    func viewLoaded()
}

//MARK: Interactor -
protocol WildcardsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func wildcardsFetched(_ wildcards : [WildcardEntity])
}

protocol WildcardsInteractorInputProtocol: class {

    var output: WildcardsInteractorOutputProtocol?  { get set }
    
    /* Presenter -> Interactor */
    func fetchWildcards()
}

//MARK: View -
protocol WildcardsViewProtocol: class {

    var presenter: WildcardsPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func setWildcards(_ wildcards : [WildcardEntity])
    func showNoUsersAlert()
}
